name: Playwright Tests
on:
  push:
    branches:
      - master
    paths:
      # Only run Playwright when these files change
      - 'e2e/**'
      - 'app/**'
      - 'components/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'e2e/**'
      - 'app/**'
      - 'components/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch: 

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm test:e2e

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7